server:
  port: 8082

spring:
  application:
    name: alert-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/anomanet}
    username: ${POSTGRES_USER:anomanet}
    password: ${POSTGRES_PASSWORD:anomanet123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: alert-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topics:
    alerts-generated: alerts.generated

anomanet:
  threshold:
    anoma-score: ${ANOMASCORE_THRESHOLD:0.65}
    pep: ${PEP_THRESHOLD:0.45}
